-keep,allowoptimization public class com.github.ppaszkiewicz.tools.toolbox.** { public *; protected *;}
-keep,allowoptimization interface com.github.ppaszkiewicz.tools.toolbox.** { public *;}
-keep,allowoptimization enum com.github.ppaszkiewicz.tools.toolbox.** { public *;}